// Generated by CoffeeScript 2.8.0

var data, item, result, sum, value, x;

x = y ?? "default";

result = a ?? b ?? c ?? "final";

data = getData() ?? {};

value = obj.prop ?? 0;

sum = (x ?? 0) + (y ?? 0);

item = arr[index] ?? defaultItem;

export var helper = config ?? {};
