// Generated by CoffeeScript 2.8.0
(function() {
  

  const testFunc = function() {
    console.log("Starting");
    const ref = [1, 2, 3];
    results = [];
    for (let i = 0, len = ref.length; i < len; i++) {
      const x = ref[i];
      results.push(x * 2);
    }
    return results;
  };

  let result = testFunc();

  console.log("Result:", result);

}).call(this);
