// Generated by CoffeeScript 2.8.0
(function() {
  

  const f = function() {
    const ref = [1, 2, 3];
    results = [];
    for (let i = 0, len = ref.length; i < len; i++) {
      const x = ref[i];
      results.push(x * 2);
    }
    return results;
  };

  console.log(f());

}).call(this);
