// Generated by CoffeeScript 2.8.0
(function() {
  

  const test = function() {
    try {
      let stats = fs.statSync('test.txt');
      let code = fs.readFileSync('test.txt');
    } catch (error) {
      let err = error;
      console.log("Error:", err.message);
    }
    console.log("Stats:", stats);
    return console.log("Code:", code);
  };

  test();

}).call(this);
