// Generated by CoffeeScript 2.8.0


const test = function() {
  let str = "hello world hello";
  while (match = /hello/g.exec(str)) {
    console.log(match);
  }
  let items = [[1, 2], [3, 4], [5, 6]];
  let i = 0;
  const results = [];
  while (item = items[i++]) {
    [a, b] = item;
    results.push(console.log(a, b));
  }
  return results;
};

test();
