// Generated by CoffeeScript 2.8.0


const test = function() {
  if (!(match = /test/.exec("test"))) {
    return 0;
  }
  console.log(match);
  [a, b] = [1, 2];
  return console.log(a, b);
};

test();
