// Generated by CoffeeScript 3.0.0
(function() {
  
  let Greeter, a, b, greeter, square;

  console.log(`Current time: ${new Date().toLocaleTimeString()}`);

  square = (x) => x * x;

  console.log(`5 squared = ${square(5)}`);

  a = 10;

  b = null;

  b ??= 20;

  console.log(`b = ${b}`);

  Greeter = class Greeter {
    constructor(name) {
      this.name = name;
    }

    greet() {
      return console.log(`Hello, ${this.name}!`);
    }

  };

  greeter = new Greeter("World");

  greeter.greet();

}).call(this);
