// Generated by CoffeeScript 2.7.0
(function() {
  // ==============================================================================
  // ES5 Backend - Converts Solar directives (pure data) to CoffeeScript AST nodes
  // ==============================================================================
  var ES5Backend,
    hasProp = {}.hasOwnProperty;

  ES5Backend = class ES5Backend {
    constructor(options1 = {}, ast = {}) {
      this.options = options1;
      this.ast = ast;
      this.currentDirective = null;
      this.currentRule = null;
      this.currentLookup = null;
    }

    // Helper to ensure node has location data to avoid errors in AST operations
    _ensureLocationData(node) {
      if (typeof node === 'object' && node !== null) {
        if (node.locationData == null) {
          node.locationData = {
            first_line: 0,
            first_column: 0,
            last_line: 0,
            last_column: 0,
            range: [0, 0]
          };
        }
        if (typeof node.updateLocationDataIfMissing === "function") {
          node.updateLocationDataIfMissing(node.locationData);
        }
      }
      return node;
    }

    // Shorthand for adding dummy location data
    _ensureLocation(node) {
      if (node != null) {
        if (node.locationData == null) {
          node.locationData = {
            first_line: 0,
            first_column: 0,
            last_line: 0,
            last_column: 0,
            range: [0, 0]
          };
        }
      }
      return node;
    }

    // Helper to convert primitive values to AST nodes
    _toNode(value) {
      if (value instanceof this.ast.Base) {
        return value;
      }
      if (typeof value === 'string') {
        return new this.ast.IdentifierLiteral(value);
      }
      if (typeof value === 'number') {
        return new this.ast.NumberLiteral(value);
      }
      if (typeof value === 'boolean') {
        return new this.ast.BooleanLiteral(value);
      }
      return value;
    }

    // Helper to convert base + properties to Value node
    _toValue(base, properties) {
      var props;
      props = Array.isArray(properties) ? properties : [];
      // Handle existing Value
      if (base instanceof this.ast.Value) {
        if (props.length) {
          base.add(props);
        }
        return base;
      }
      if ((base != null) && !(base instanceof this.ast.Base)) {
        // Ensure base is a node
        base = this._toNode(base);
      }
      return new this.ast.Value(base, props);
    }

    // Main entry point (called by parser as 'reduce')
    reduce(values, positions, stackTop, symbolCount, directive) {
      var handler, lookup, o, outName, ref, ref1, ref2, ref3, result, util;
      // Create lookup function to access stack values
      lookup = function(index) {
        return values[stackTop - symbolCount + 1 + index];
      };
      this.currentDirective = directive;
      this.currentRule = directive;
      this.currentLookup = lookup; // Store lookup for use in $()
      
      // Create smart proxy that auto-resolves properties
      handler = {
        get: function(target, prop) {
          var idx;
          if (prop in target) {
            // Return directive properties first
            return target[prop];
          }
          // Handle numeric indices for stack access
          if (typeof prop === 'string' && /^\d+$/.test(prop)) {
            idx = parseInt(prop, 10) - 1; // Convert to 0-based
            if (idx >= 0) {
              return lookup(idx);
            }
          }
          // Handle $N syntax
          if (typeof prop === 'string' && prop[0] === '$') {
            idx = parseInt(prop.slice(1), 10) - 1; // Convert to 0-based
            if (idx >= 0) {
              return lookup(idx);
            }
          }
          return void 0;
        }
      };
      // Create smart directive object
      o = new Proxy(directive, handler);
      // Process the directive
      result = this.process(o);
      if ((ref = global.process) != null ? (ref1 = ref.env) != null ? ref1.SOLAR_DEBUG : void 0 : void 0) {
        util = require('util');
        outName = (ref2 = result != null ? (ref3 = result.constructor) != null ? ref3.name : void 0 : void 0) != null ? ref2 : typeof result;
        console.log("[Solar] result:", outName, util.inspect(result, {
          depth: 3,
          colors: true
        }));
      }
      return result;
    }

    // Process a directive with smart resolution, ordered by most common to least
    process(o) {
      if (o.$ast != null) {
        return this.processAst(o);
      }
      if (o.$use != null) {
        return this.processUse(o);
      }
      if (o.$ops != null) {
        return this.processOps(o);
      }
      if (o.$arr != null) {
        return this.processArr(o);
      }
      return this.$(o);
    }

    // Smart resolver - handles all types of references
    $(value) {
      var key, result, val;
      if (value == null) {
        return value;
      }
      // Numbers are stack positions (1-based)
      if (typeof value === 'number') {
        if (this.currentLookup) {
          return this.currentLookup(value - 1);
        }
        return value;
      }
      // Arrays - resolve each item
      if (Array.isArray(value)) {
        return value.map((item) => {
          return this.$(item);
        });
      }
      // Objects with directives - process them
      if (typeof value === 'object') {
        if (value.$ast || value.$ops || value.$use || value.$arr) {
          return this.process(value);
        }
        // Regular objects - resolve properties
        result = {};
        for (key in value) {
          if (!hasProp.call(value, key)) continue;
          val = value[key];
          result[key] = this.$(val);
        }
        return result;
      }
      // Everything else passes through
      return value;
    }

    // Process $arr directives
    processArr(o) {
      var items;
      items = this.$(o.$arr);
      if (Array.isArray(items)) {
        return items;
      } else {
        return [items];
      }
    }

    // Process $use directives
    processUse(o) {
      var name1, ref, target;
      target = this.$(o.$use);
      if (o.method != null) {
        return target != null ? typeof target[name1 = o.method] === "function" ? target[name1](...((ref = o.args) != null ? ref : [])) : void 0 : void 0;
      }
      if (o.prop != null) {
        return target != null ? target[o.prop] : void 0;
      }
      if (o.index != null) {
        return target != null ? target[o.index] : void 0;
      }
      return target;
    }

    // Process $ops directives
    processOps(o) {
      var accessor, body, elseBody, i, ifNode, item, len, loopNode, ref, ref1, ref2, ref3, ref4, ref5, resolved, result, sourceInfo, util, value;
      switch (o.$ops) {
        case 'array':
          result = [];
          if (o.append != null) {
            ref = o.append;
            for (i = 0, len = ref.length; i < len; i++) {
              item = ref[i];
              resolved = this.$(item);
              if (Array.isArray(resolved)) {
                result.push(...resolved);
              } else if (resolved != null) {
                result.push(resolved);
              }
            }
          }
          return result;
        case 'if':
          // Handle addElse operation for if-else chains
          if (o.addElse != null) {
            [ifNode, elseBody] = o.addElse.map((item) => {
              return this.$(item);
            });
            this._ensureLocationData(ifNode);
            this._ensureLocationData(elseBody);
            ifNode.addElse(elseBody);
            return ifNode;
          }
          break;
        case 'value':
          // Handle adding accessors to Values
          if (o.add != null) {
            [value, accessor] = o.add.map((item) => {
              return this.$(item);
            });
            if (value instanceof this.ast.Value) {
              return value.add(accessor);
            } else {
              return this._toValue(value, [accessor]);
            }
          }
          break;
        case 'loop':
          // Handle different loop operations
          if (o.addSource != null) {
            // addSource: [1, 2] means ForStart is at position 1, ForSource at position 2
            [loopNode, sourceInfo] = o.addSource.map((item) => {
              return this.$(item);
            });
            this._ensureLocationData(loopNode);
            if (sourceInfo != null) {
              this._ensureLocationData(sourceInfo);
            }
            if ((loopNode != null ? loopNode.addSource : void 0) != null) {
              loopNode.addSource(sourceInfo);
            }
            return loopNode;
          }
          if (o.addBody != null) {
            if ((ref1 = global.process) != null ? (ref2 = ref1.env) != null ? ref2.SOLAR_DEBUG : void 0 : void 0) {
              console.log("[Solar] loop.addBody operation:", o.addBody);
            }
            [loopNode, body] = o.addBody.map((item) => {
              return this.$(item);
            });
            body = this.ast.Block.wrap(body);
            if ((ref3 = global.process) != null ? (ref4 = ref3.env) != null ? ref4.SOLAR_DEBUG : void 0 : void 0) {
              util = require('util');
              console.log("[Solar] loop.addBody loopNode:", loopNode != null ? (ref5 = loopNode.constructor) != null ? ref5.name : void 0 : void 0);
              console.log("[Solar] loop.addBody body:", util.inspect(body, {
                depth: 2,
                colors: true
              }));
            }
            this._ensureLocationData(loopNode);
            this._ensureLocationData(body);
            loopNode.addBody(body);
            return loopNode;
          }
      }
      // Catchall for any missing $ops directive handlers
      console.warn("Missing $ops directive handler:", o);
      return new this.ast.Literal(`# Missing $ops directive handler for: ${JSON.stringify(o)}`);
    }

    // Process $ast directives - the main AST node creation
    processAst(o) {
      var args, body, context, expression, expressions, forNode, ifNode, name, operator, options, ref, ref1, value, variable, whileNode;
      switch (o.$ast) {
        // === CORE EXPRESSIONS (Very High Frequency) ===

          // Values and property access - the most fundamental operations
        case 'Value':
          return this._toValue(this.$(o.base), (ref = this.$(o.properties)) != null ? ref : []);
        case 'IdentifierLiteral':
          return new this.ast.IdentifierLiteral(this.$(o.value));
        case 'Literal':
          return new this.ast.Literal(this.$(o.value));
        case 'NumberLiteral':
          return new this.ast.NumberLiteral(this.$(o.value));
        case 'StringLiteral':
          return this._ensureLocation(new this.ast.StringLiteral(this.$(o.value), {
            quote: this.$(o.quote),
            initialChunk: this.$(o.initialChunk),
            finalChunk: this.$(o.finalChunk),
            indent: this.$(o.indent),
            double: this.$(o.double),
            heregex: this.$(o.heregex)
          }));
        // Basic operations - assignments, calls, operators
        case 'Assign':
          variable = this.$(o.variable);
          value = this.$(o.value);
          context = this.$(o.context);
          if (context === 'object' && variable instanceof this.ast.Value && variable.base instanceof this.ast.ThisLiteral) {
            // Mark @-based object-context assignments as static (for class bodies)
            variable.this = true;
          }
          if (o.operator != null) {
            // Handle compound assignment (+=, -=, etc.)
            operator = this.$(o.operator);
          }
          if (operator && operator !== '=') {
            value = new this.ast.Op(operator.replace('=', ''), variable, value);
          }
          options = o.operatorToken ? {
            operatorToken: this.$(o.operatorToken)
          } : {};
          return new this.ast.Assign(variable, value, context, options);
        case 'Call':
          return new this.ast.Call(this.$(o.variable), this.$(o.args) || [], this.$(o.soak));
        case 'Op':
          // Process args - preserve undefineds for proper positioning
          args = ((ref1 = o.args) != null ? ref1.map((arg) => {
            return this.$(arg);
          }) : void 0) || [];
          if ((o.invertOperator != null) || (o.originalOperator != null)) {
            options = {};
            if (o.invertOperator != null) {
              options.invertOperator = this.$(o.invertOperator);
            }
            if (o.originalOperator != null) {
              options.originalOperator = this.$(o.originalOperator);
            }
            args.push(options);
          }
          return new this.ast.Op(...args);
        // Property access patterns
        case 'Access':
          name = this.$(o.name);
          if (name instanceof this.ast.IdentifierLiteral) {
            name = new this.ast.PropertyName(name.value);
          }
          return new this.ast.Access(name, {
            soak: this.$(o.soak),
            shorthand: this.$(o.shorthand)
          });
        case 'Index':
          return new this.ast.Index(this.$(o.index));
        case 'PropertyName':
          return new this.ast.PropertyName(this.$(o.value));
        // === CONTROL FLOW & STRUCTURE (High Frequency) ===

          // Program structure
        case 'Block':
          expressions = this.$(o.expressions);
          return new this.ast.Block((expressions instanceof this.ast.Block ? expressions.expressions : expressions) || []);
        case 'Root':
          body = this.ast.Block.wrap(this.$(o.body));
          if (this.options.makeReturn) {
            body.makeReturn();
          }
          return new this.ast.Root(body);
        // Control flow statements
        case 'If':
          ifNode = new this.ast.If(this.$(o.condition), this.ast.Block.wrap(this.$(o.body)), {
            type: (this.$(o.invert) ? 'unless' : this.$(o.type)),
            postfix: this.$(o.postfix)
          });
          if (o.elseBody != null) {
            ifNode.addElse(this.ast.Block.wrap(this.$(o.elseBody)));
          }
          return ifNode;
        case 'While':
          whileNode = new this.ast.While(this.$(o.condition), {
            invert: this.$(o.invert),
            guard: this.$(o.guard),
            isLoop: this.$(o.isLoop)
          });
          whileNode.body = this.ast.Block.wrap(this.$(o.body));
          return whileNode;
        case 'For':
          body = this._ensureLocation(this.ast.Block.wrap(this.$(o.body)));
          forNode = new this.ast.For(body, {
            name: this.$(o.name),
            index: this.$(o.index),
            source: this.$(o.source)
          });
          if (o.await != null) {
            forNode.await = this.$(o.await);
          }
          if (o.own != null) {
            forNode.own = this.$(o.own);
          }
          return this._ensureLocation(forNode);
        case 'Return':
          return new this.ast.Return(this.$(o.expression));
        // === FUNCTIONS & CLASSES (Medium-High Frequency) ===
        case 'Code':
          return new this.ast.Code(this.$(o.params) || [], this.ast.Block.wrap(this.$(o.body)));
        case 'FuncGlyph':
          return new this.ast.FuncGlyph(this.$(o.value) || '->');
        case 'Class':
          return new this.ast.Class(this.$(o.variable), this.$(o.parent), this.$(o.body));
        case 'Param':
          name = this.$(o.name);
          if (name instanceof this.ast.Value && name.base instanceof this.ast.ThisLiteral) {
            name.this = true;
          }
          return new this.ast.Param(name, this.$(o.value), this.$(o.splat));
        // === DATA STRUCTURES (Medium Frequency) ===
        case 'Obj':
          return new this.ast.Obj(this.$(o.properties) || [], this.$(o.generated));
        case 'Arr':
          return new this.ast.Arr(this.$(o.objects) || []);
        case 'Range':
          return new this.ast.Range(this.$(o.from), this.$(o.to), this.$(o.exclusive) ? 'exclusive' : void 0);
        case 'Slice':
          return new this.ast.Slice(this.$(o.range));
        case 'Expansion':
          return new this.ast.Expansion(); // Rest/spread operator (...)
        
          // === COMMON LITERALS (Medium Frequency) ===
        case 'BooleanLiteral':
          return new this.ast.BooleanLiteral(this.$(o.value));
        case 'ThisLiteral':
          return new this.ast.ThisLiteral();
        case 'NullLiteral':
          return new this.ast.NullLiteral();
        case 'UndefinedLiteral':
          return new this.ast.UndefinedLiteral();
        case 'RegexLiteral':
          return new this.ast.RegexLiteral(this.$(o.value), {
            delimiter: this.$(o.delimiter),
            heregexCommentTokens: this.$(o.heregexCommentTokens)
          });
        case 'PassthroughLiteral':
          return new this.ast.PassthroughLiteral(this.$(o.value));
        case 'StatementLiteral':
          return new this.ast.StatementLiteral(this.$(o.value));
        case 'ComputedPropertyName':
          return new this.ast.ComputedPropertyName(this.$(o.expression) || this.$(o.name) || this.$(o.value));
        // === STRING INTERPOLATION (Low-Medium Frequency) ===
        case 'StringWithInterpolations':
          return new this.ast.StringWithInterpolations(this.ast.Block.wrap(this.$(o.body)));
        case 'Interpolation':
          expression = this.$(o.expression);
          if (expression != null) {
            return new this.ast.Interpolation(expression);
          } else {
            return new this.ast.EmptyInterpolation();
          }
          break;
        // === SPECIAL OPERATIONS (Low Frequency) ===

          // Switch statements
        case 'Switch':
          return new this.ast.Switch(this.$(o.subject), this.$(o.cases) || [], this.$(o.otherwise));
        case 'SwitchWhen':
          return new this.ast.SwitchWhen([].concat(this.$(o.conditions)), this.$(o.body));
        // Super calls
        case 'Super':
          return new this.ast.Super(this.$(o.accessor), this.$(o.superLiteral));
        case 'SuperCall':
          return new this.ast.SuperCall(this.$(o.variable), this.$(o.args) || [], this.$(o.soak));
        // Other operations
        case 'Existence':
          return new this.ast.Existence(this.$(o.expression));
        case 'Parens':
          return new this.ast.Parens(this.$(o.body));
        case 'Splat':
          return new this.ast.Splat(this.$(o.name), {
            postfix: this.$(o.postfix)
          });
        // === ERROR HANDLING (Low Frequency) ===
        case 'Try':
          return new this.ast.Try(this.$(o.attempt), this.$(o.catch), this.$(o.ensure));
        case 'Catch':
          return new this.ast.Catch(this.$(o.recovery) || this.$(o.body), this.$(o.variable) || this.$(o.errorVariable));
        case 'Throw':
          return new this.ast.Throw(this.$(o.expression));
        // === MODULES (Low Frequency) ===

          // Import statements
        case 'ImportDeclaration':
          return new this.ast.ImportDeclaration(this.$(o.clause), this.$(o.source));
        case 'ImportClause':
          return new this.ast.ImportClause(this.$(o.defaultBinding), this.$(o.namedImports));
        case 'ImportSpecifierList':
          return new this.ast.ImportSpecifierList(this.$(o.specifiers) || []);
        case 'ImportSpecifier':
          return new this.ast.ImportSpecifier(this.$(o.imported), this.$(o.local));
        case 'ImportDefaultSpecifier':
          return new this.ast.ImportDefaultSpecifier(this.$(o.name) || this.$(o.value) || this.$(o));
        case 'ImportNamespaceSpecifier':
          return new this.ast.ImportNamespaceSpecifier(this.$(o.star), this.$(o.local));
        // Export statements
        case 'ExportNamedDeclaration':
          return new this.ast.ExportNamedDeclaration(this.$(o.clause), this.$(o.source), this.$(o.assertions));
        case 'ExportDefaultDeclaration':
          return new this.ast.ExportDefaultDeclaration(this.$(o.declaration) || this.$(o.value));
        case 'ExportAllDeclaration':
          return new this.ast.ExportAllDeclaration(this.$(o.exported), this.$(o.source), this.$(o.assertions));
        case 'ExportSpecifierList':
          return new this.ast.ExportSpecifierList(this.$(o.specifiers) || []);
        case 'ExportSpecifier':
          return new this.ast.ExportSpecifier(this.$(o.local), this.$(o.exported));
        // === ADVANCED/RARE FEATURES (Very Low Frequency) ===

          // Advanced literals
        case 'InfinityLiteral':
          return new this.ast.InfinityLiteral();
        case 'NaNLiteral':
          return new this.ast.NaNLiteral();
        case 'DefaultLiteral':
          return new this.ast.DefaultLiteral(this.$(o.value));
        // Advanced operations
        case 'YieldReturn':
          return new this.ast.YieldReturn(this.$(o.expression), {
            returnKeyword: this.$(o.returnKeyword)
          });
        case 'AwaitReturn':
          return new this.ast.AwaitReturn(this.$(o.expression), {
            returnKeyword: this.$(o.returnKeyword)
          });
        case 'DynamicImportCall':
          return new this.ast.DynamicImportCall(this.$(o.variable), this.$(o.args) || []);
        case 'DynamicImport':
          return new this.ast.DynamicImport();
        case 'TaggedTemplateCall':
          return new this.ast.TaggedTemplateCall(this.$(o.variable), this.$(o.template), this.$(o.soak));
        case 'MetaProperty':
          return new this.ast.MetaProperty(this.$(o.identifier), this.$(o.accessor));
        case 'RegexWithInterpolations':
          return new this.ast.RegexWithInterpolations(this.$(o.invocation), {
            heregexCommentTokens: this.$(o.heregexCommentTokens)
          });
        // Rare array operation
        case 'Elision':
          return new this.ast.Elision(); // Sparse array holes
        default:
          console.warn("Unknown $ast type:", o.$ast);
          return new this.ast.Literal(`# Missing AST node: ${o.$ast}`);
      }
    }

  };

  module.exports = ES5Backend;

}).call(this);
