// Generated by CoffeeScript 2.9.0


const x = 5;

let y = 10;

y = y + 1;

const double = function(n) {
  return n * 2;
};

const Test = class Test {
  constructor(name) {
    this.name = name;
    console.log(`Creating Test: ${this.name}`);
  }

};

const result = double(x);
