// Generated by CoffeeScript 2.8.0
(function() {
  

  const test1 = function() {
    [a, b, c] = [1, 2, 3];
    return console.log(a, b, c);
  };

  const test2 = function() {
    [x, [y, z]] = [1, [2, 3]];
    return console.log(x, y, z);
  };

  const test3 = function() {
    ({name, age} = {
      name: 'Bob',
      age: 30
    });
    return console.log(name, age);
  };

  const test4 = function() {
    let existing = {};
    [existing.a, existing.b, newVar] = [1, 2, 3];
    return console.log(newVar);
  };

  test1();

  test2();

  test3();

  test4();

}).call(this);
