// Generated by CoffeeScript 2.8.0
var run;

run = function() {
  var i, len, ref, results, x;
  ref = [1, 2, 3];
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    x = ref[i];
    results.push(x * 2);
  }
  return results;
};

console.log(run());
