// Generated by CoffeeScript 2.8.0

var base64encode, checkShebangLine, getSourceMap, lexer, registerCompiled, withPrettyErrors;

import {
  Lexer
} from './lexer';

import {
  parser
} from './parser';

import * as helpers from './helpers';

import SourceMap from './sourcemap';

import Backend from './backend';

import * as nodesModule from './nodes';

import packageJson from '../../package.json';

export var VERSION = packageJson.version;

export var FILE_EXTENSIONS = ['.coffee'];

export {
  helpers
};

({getSourceMap, registerCompiled} = SourceMap);

export {
  registerCompiled
};

base64encode = function(src) {
  if (typeof Buffer === 'function') {
    return Buffer.from(src).toString('base64');
  } else {
    throw new Error('Unable to base64 encode inline sourcemap.');
  }
};

withPrettyErrors = function(fn) {
  return function(code, options = {}) {
    var err;
    try {
      return fn.call(this, code, options);
    } catch (error) {
      err = error;
      if (typeof code !== 'string') {
        throw err;
      }
      throw helpers.updateSyntaxError(err, code, options.filename);
    }
  };
};

export var compile = withPrettyErrors(function(code, options = {}) {
  var ast, currentColumn, currentLine, encoded, filename, fragment, fragments, generateSourceMap, header, j, js, k, len, len1, map, newLines, nodes, range, ref, sourceCodeLastLine, sourceCodeNumberOfLines, sourceMapDataURI, sourceURL, token, tokens, v3SourceMap;
  options = Object.assign({}, options);
  generateSourceMap = options.sourceMap || options.inlineMap || (options.filename == null);
  filename = options.filename || helpers.anonymousFileName();
  checkShebangLine(filename, code);
  if (generateSourceMap) {
    map = new SourceMap();
  }
  tokens = lexer.tokenize(code, options);
  options.referencedVars = (function() {
    var j, len, results;
    results = [];
    for (j = 0, len = tokens.length; j < len; j++) {
      token = tokens[j];
      if (token[0] === 'IDENTIFIER') {
        results.push(token[1]);
      }
    }
    return results;
  })();
  if (!((options.bare != null) && options.bare === true)) {
    for (j = 0, len = tokens.length; j < len; j++) {
      token = tokens[j];
      if ((ref = token[0]) === 'IMPORT' || ref === 'EXPORT') {
        options.bare = true;
        break;
      }
    }
  }
  parser.yy.backend = new Backend(options, parser.yy);
  nodes = parser.parse(tokens);
  if (options.ast) {
    nodes.allCommentTokens = helpers.extractAllCommentTokens(tokens);
    sourceCodeNumberOfLines = (code.match(/\r?\n/g) || '').length + 1;
    sourceCodeLastLine = /.*$/.exec(code)[0];
    ast = nodes.ast(options);
    range = [0, code.length];
    ast.start = ast.program.start = range[0];
    ast.end = ast.program.end = range[1];
    ast.range = ast.program.range = range;
    ast.loc.start = ast.program.loc.start = {
      line: 1,
      column: 0
    };
    ast.loc.end.line = ast.program.loc.end.line = sourceCodeNumberOfLines;
    ast.loc.end.column = ast.program.loc.end.column = sourceCodeLastLine.length;
    ast.tokens = tokens;
    return ast;
  }
  fragments = nodes.compileToFragments(options);
  currentLine = 0;
  if (options.header) {
    currentLine += 1;
  }
  if (options.shiftLine) {
    currentLine += 1;
  }
  currentColumn = 0;
  js = "";
  for (k = 0, len1 = fragments.length; k < len1; k++) {
    fragment = fragments[k];
    if (generateSourceMap) {
      if (fragment.locationData && !/^[;\s]*$/.test(fragment.code)) {
        map.add([fragment.locationData.first_line, fragment.locationData.first_column], [currentLine, currentColumn], {
          noReplace: true
        });
      }
      newLines = helpers.count(fragment.code, "\n");
      currentLine += newLines;
      if (newLines) {
        currentColumn = fragment.code.length - (fragment.code.lastIndexOf("\n") + 1);
      } else {
        currentColumn += fragment.code.length;
      }
    }
    js += fragment.code;
  }
  if (options.header) {
    header = `Generated by CoffeeScript ${VERSION}`;
    js = `// ${header}\n${js}`;
  }
  if (generateSourceMap) {
    v3SourceMap = map.generate(options, code);
  }
  if (options.inlineMap) {
    encoded = base64encode(JSON.stringify(v3SourceMap));
    sourceMapDataURI = `//# sourceMappingURL=data:application/json;base64,${encoded}`;
    sourceURL = `//# sourceURL=${filename}`;
    js = `${js}\n${sourceMapDataURI}\n${sourceURL}`;
  }
  registerCompiled(filename, code, map);
  if (options.sourceMap) {
    return {
      js,
      sourceMap: map,
      v3SourceMap: JSON.stringify(v3SourceMap, null, 2)
    };
  } else {
    return js;
  }
});

export var tokens = withPrettyErrors(function(code, options) {
  return lexer.tokenize(code, options);
});

export var nodes = withPrettyErrors(function(source, options) {
  if (typeof source === 'string') {
    source = lexer.tokenize(source, options);
  }
  parser.yy.backend = new Backend(options, parser.yy);
  return parser.parse(source);
});

lexer = new Lexer();

parser.lexer = {
  yylloc: {
    range: []
  },
  options: {
    ranges: true
  },
  lex: function() {
    var tag, token;
    token = parser.tokens[this.pos++];
    if (token) {
      [tag, this.yytext, this.yylloc] = token;
      parser.errorToken = token.origin || token;
      this.yylineno = this.yylloc.first_line;
    } else {
      tag = '';
    }
    return tag;
  },
  setInput: function(tokens) {
    parser.tokens = tokens;
    return this.pos = 0;
  },
  upcomingInput: function() {
    return '';
  }
};

parser.yy = {...nodesModule};

parser.yy.parseError = function(message, {token}) {
  var errorLoc, errorTag, errorText, errorToken, parserTokens;
  ({
    errorToken,
    tokens: parserTokens
  } = parser);
  [errorTag, errorText, errorLoc] = errorToken;
  errorText = (function() {
    switch (false) {
      case errorToken !== parserTokens[parserTokens.length - 1]:
        return 'end of input';
      case errorTag !== 'INDENT' && errorTag !== 'OUTDENT':
        return 'indentation';
      case errorTag !== 'IDENTIFIER' && errorTag !== 'NUMBER' && errorTag !== 'INFINITY' && errorTag !== 'STRING' && errorTag !== 'STRING_START' && errorTag !== 'REGEX' && errorTag !== 'REGEX_START':
        return errorTag.replace(/_START$/, '').toLowerCase();
      default:
        return helpers.nameWhitespaceCharacter(errorText);
    }
  })();
  return helpers.throwSyntaxError(`unexpected ${errorText}`, errorLoc);
};

export var patchStackTrace = function() {
  var formatSourcePosition, getSourceMapping;
  formatSourcePosition = function(frame, getSourceMapping) {
    var as, column, fileLocation, filename, functionName, isConstructor, isMethodCall, line, methodName, source, tp, typeName;
    filename = void 0;
    fileLocation = '';
    if (frame.isNative()) {
      fileLocation = "native";
    } else {
      if (frame.isEval()) {
        filename = frame.getScriptNameOrSourceURL();
        if (!filename) {
          fileLocation = `${frame.getEvalOrigin()}, `;
        }
      } else {
        filename = frame.getFileName();
      }
      filename || (filename = "<anonymous>");
      line = frame.getLineNumber();
      column = frame.getColumnNumber();
      source = getSourceMapping(filename, line, column);
      fileLocation = source ? `${filename}:${source[0]}:${source[1]}` : `${filename}:${line}:${column}`;
    }
    functionName = frame.getFunctionName();
    isConstructor = frame.isConstructor();
    isMethodCall = !(frame.isToplevel() || isConstructor);
    if (isMethodCall) {
      methodName = frame.getMethodName();
      typeName = frame.getTypeName();
      if (functionName) {
        tp = as = '';
        if (typeName && functionName.indexOf(typeName)) {
          tp = `${typeName}.`;
        }
        if (methodName && functionName.indexOf(`.${methodName}`) !== functionName.length - methodName.length - 1) {
          as = ` [as ${methodName}]`;
        }
        return `${tp}${functionName}${as} (${fileLocation})`;
      } else {
        return `${typeName}.${methodName || '<anonymous>'} (${fileLocation})`;
      }
    } else if (isConstructor) {
      return `new ${functionName || '<anonymous>'} (${fileLocation})`;
    } else if (functionName) {
      return `${functionName} (${fileLocation})`;
    } else {
      return fileLocation;
    }
  };
  getSourceMapping = function(filename, line, column) {
    var answer, sourceMap;
    sourceMap = getSourceMap(filename, line, column);
    if (sourceMap != null) {
      answer = sourceMap.sourceLocation([line - 1, column - 1]);
    }
    if (answer != null) {
      return [answer[0] + 1, answer[1] + 1];
    } else {
      return null;
    }
  };
  return Error.prepareStackTrace = function(err, stack) {
    var frame, frames, i;
    frames = (function() {
      var j, len, results;
      results = [];
      for (i = j = 0, len = stack.length; j < len; i = ++j) {
        frame = stack[i];
        if (i > 10) {
          break;
        }
        results.push(`    at ${formatSourcePosition(frame, getSourceMapping)}`);
      }
      return results;
    })();
    return `${err.toString()}\n${frames.join('\n')}\n`;
  };
};

checkShebangLine = function(file, input) {
  var args, firstLine, ref, rest;
  firstLine = input.split(/$/m, 1)[0];
  rest = firstLine != null ? firstLine.match(/^#!\s*([^\s]+\s*)(.*)/) : void 0;
  args = rest != null ? (ref = rest[2]) != null ? ref.split(/\s/).filter(function(s) {
    return s !== '';
  }) : void 0 : void 0;
  if ((args != null ? args.length : void 0) > 1) {
    console.error(`The script to be run begins with a shebang line with more than one
argument. This script will fail on platforms such as Linux which only
allow a single argument.`);
    console.error(`The shebang line was: '${firstLine}' in file '${file}'`);
    return console.error(`The arguments were: ${JSON.stringify(args)}`);
  }
};

export default {VERSION, FILE_EXTENSIONS, helpers, registerCompiled, compile, tokens, nodes, patchStackTrace};
