// Generated by CoffeeScript 2.8.0

import * as CoffeeScript from './coffeescript.js';

import fs from 'fs';

import vm from 'vm';

export let compile = CoffeeScript.compile;

export let run = function(code, options = {}) {
  let compiled;
  compiled = CoffeeScript.compile(code, {
    bare: true,
    ...options
  });
  return vm.runInThisContext(compiled.js ?? compiled);
};

export let evalCode = function(code, options = {}) {
  let compiled, sandbox;
  if (!(code = code.trim())) {
    return;
  }
  sandbox = options.sandbox ?? global;
  compiled = CoffeeScript.compile(code, {
    bare: true,
    ...options
  });
  if (sandbox === global) {
    return vm.runInThisContext(compiled);
  } else {
    return vm.runInContext(compiled, vm.createContext(sandbox));
  }
};

export let compileFile = function(filename, options = {}) {
  let source;
  source = fs.readFileSync(filename, 'utf8');
  return CoffeeScript.compile(source, {filename, ...options});
};

export let runFile = function(filename, options = {}) {
  let compiled;
  compiled = compileFile(filename, options);
  return vm.runInThisContext(compiled.js ?? compiled);
};

export * from './coffeescript.js';

export { default } from './coffeescript.js';
