// Generated by CoffeeScript 2.8.0
let CoffeeScript, addHistory, addMultilineHandler, fs, getCommandId, merge, nodeREPL, path, replDefaults, runInContext, sawSIGINT, updateSyntaxError, vm;

fs = require('fs');

path = require('path');

vm = require('vm');

nodeREPL = require('repl');

CoffeeScript = require('./');

({merge, updateSyntaxError} = require('./helpers'));

sawSIGINT = false;

replDefaults = {
  prompt: 'coffee> ',
  historyFile: (() => {
    let historyPath;
    historyPath = process.env.XDG_CACHE_HOME || process.env.HOME;
    if (historyPath) {
      return path.join(historyPath, '.coffee_history');
    }
  })(),
  historyMaxInputSize: 10240,
  eval: (input, context, filename, cb) => {
    let Assign, Block, Call, Code, Literal, Root, Value, ast, err, isAsync, js, ref, ref1, referencedVars, result, token, tokens;
    input = input.replace(/\uFF00/g, '\n');
    input = input.replace(/^\(([\s\S]*)\n\)$/m, '$1');
    input = input.replace(/^\s*try\s*{([\s\S]*)}\s*catch.*$/m, '$1');
    ({Block, Assign, Value, Literal, Call, Code, Root} = require(process.env.ES6 ? './nodes' : './nodes5'));
    try {
      tokens = CoffeeScript.tokens(input);
      if (tokens.length >= 2 && tokens[0].generated && ((ref = tokens[0].comments) != null ? ref.length : void 0) !== 0 && `${tokens[0][1]}` === '' && tokens[1][0] === 'TERMINATOR') {
        tokens = tokens.slice(2);
      }
      if (tokens.length >= 1 && tokens[tokens.length - 1].generated && ((ref1 = tokens[tokens.length - 1].comments) != null ? ref1.length : void 0) !== 0 && `${tokens[tokens.length - 1][1]}` === '') {
        tokens.pop();
      }
      referencedVars = (() => {
        let i, len, results;
        results = [];
        for (i = 0, len = tokens.length; i < len; i++) {
          token = tokens[i];
          if (token[0] === 'IDENTIFIER') {
            results.push(token[1]);
          }
        }
        return results;
      })();
      ast = CoffeeScript.nodes(tokens).body;
      ast = new Block([new Assign(new Value(new Literal('__')), ast, '=')]);
      ast = new Code([], ast);
      isAsync = ast.isAsync;
      ast = new Root(new Block([new Call(ast)]));
      js = ast.compile({
        bare: true,
        locals: Object.keys(context),
        referencedVars,
        sharedScope: true
      });
      result = runInContext(js, context, filename);
      if (isAsync) {
        result.then((resolvedResult) => {
          if (!sawSIGINT) {
            return cb(null, resolvedResult);
          }
        });
        return sawSIGINT = false;
      } else {
        return cb(null, result);
      }
    } catch (error) {
      err = error;
      updateSyntaxError(err, input);
      return cb(err);
    }
  }
};

runInContext = (js, context, filename) => {
  if (context === global) {
    return vm.runInThisContext(js, filename);
  } else {
    return vm.runInContext(js, context, filename);
  }
};

addMultilineHandler = (repl) => {
  let inputStream, multiline, nodeLineListener, origPrompt, outputStream;
  ({inputStream, outputStream} = repl);
  origPrompt = repl._prompt ?? repl.prompt;
  multiline = {
    enabled: false,
    initialPrompt: origPrompt.replace(/^[^> ]*/, (x) => x.replace(/./g, '-')),
    prompt: origPrompt.replace(/^[^> ]*>?/, (x) => x.replace(/./g, '.')),
    buffer: ''
  };
  nodeLineListener = repl.listeners('line')[0];
  repl.removeListener('line', nodeLineListener);
  repl.on('line', (cmd) => {
    if (multiline.enabled) {
      multiline.buffer += `${cmd}\n`;
      repl.setPrompt(multiline.prompt);
      repl.prompt(true);
    } else {
      repl.setPrompt(origPrompt);
      nodeLineListener(cmd);
    }
  });
  return inputStream.on('keypress', (char, key) => {
    if (!(key && key.ctrl && !key.meta && !key.shift && key.name === 'v')) {
      return;
    }
    if (multiline.enabled) {
      if (!multiline.buffer.match(/\n/)) {
        multiline.enabled = !multiline.enabled;
        repl.setPrompt(origPrompt);
        repl.prompt(true);
        return;
      }
      if ((repl.line != null) && !repl.line.match(/^\s*$/)) {
        return;
      }
      multiline.enabled = !multiline.enabled;
      repl.line = '';
      repl.cursor = 0;
      repl.output.cursorTo(0);
      repl.output.clearLine(1);
      multiline.buffer = multiline.buffer.replace(/\n/g, '\uFF00');
      repl.emit('line', multiline.buffer);
      multiline.buffer = '';
    } else {
      multiline.enabled = !multiline.enabled;
      repl.setPrompt(multiline.initialPrompt);
      repl.prompt(true);
    }
  });
};

addHistory = (repl, filename, maxSize) => {
  let buffer, fd, lastLine, readFd, size, stat;
  lastLine = null;
  try {
    stat = fs.statSync(filename);
    size = Math.min(maxSize, stat.size);
    readFd = fs.openSync(filename, 'r');
    buffer = Buffer.alloc(size);
    fs.readSync(readFd, buffer, 0, size, stat.size - size);
    fs.closeSync(readFd);
    repl.history = buffer.toString().split('\n').reverse();
    if (stat.size > maxSize) {
      repl.history.pop();
    }
    if (repl.history[0] === '') {
      repl.history.shift();
    }
    repl.historyIndex = -1;
    lastLine = repl.history[0];
  } catch (error) {}
  fd = fs.openSync(filename, 'a');
  repl.addListener('line', (code) => {
    if (code && code.length && code !== '.history' && code !== '.exit' && lastLine !== code) {
      fs.writeSync(fd, `${code}\n`);
      return lastLine = code;
    }
  });
  repl.on('SIGINT', () => sawSIGINT = true);
  repl.on('exit', () => fs.closeSync(fd));
  return repl.commands[getCommandId(repl, 'history')] = {
    help: 'Show command history',
    action: () => {
      repl.outputStream.write(`${repl.history.slice(0).reverse().join('\n')}\n`);
      return repl.displayPrompt();
    }
  };
};

getCommandId = (repl, commandName) => {
  let commandsHaveLeadingDot;
  commandsHaveLeadingDot = repl.commands['.help'] != null;
  if (commandsHaveLeadingDot) {
    return `.${commandName}`;
  } else {
    return commandName;
  }
};

module.exports = {
  start: (opts = {}) => {
    let build, major, minor, repl;
    [major, minor, build] = process.versions.node.split('.').map((n) => parseInt(n, 10));
    if (major < 6) {
      console.warn("Node 6+ required for CoffeeScript REPL");
      process.exit(1);
    }
    CoffeeScript.register();
    process.argv = ['coffee'].concat(process.argv.slice(2));
    opts = merge(replDefaults, opts);
    repl = nodeREPL.start(opts);
    if (opts.prelude) {
      runInContext(opts.prelude, repl.context, 'prelude');
    }
    repl.on('exit', () => {
      if (!repl.closed) {
        return repl.outputStream.write('\n');
      }
    });
    addMultilineHandler(repl);
    if (opts.historyFile) {
      addHistory(repl, opts.historyFile, opts.historyMaxInputSize);
    }
    repl.commands[getCommandId(repl, 'load')].help = 'Load code from a file into this REPL session';
    return repl;
  }
};
