// Generated by CoffeeScript 2.8.0
import CoffeeScript from './coffeescript.js';
import * as helpersModule from './helpers.js';



export default CoffeeScript;

export const helpers = helpersModule;

({VERSION, FILE_EXTENSIONS, compile, tokens, nodes, coffeeEval, transpile, patchStackTrace} = CoffeeScript);

export {
  VERSION,
  FILE_EXTENSIONS,
  compile,
  tokens,
  nodes,
  coffeeEval,
  transpile,
  patchStackTrace
};
