// Generated by CoffeeScript 2.8.0
import CoffeeScript from './coffeescript.js';
import * as helpersModule from './helpers.js';


export default CoffeeScript;

export const helpers = helpersModule;

export const VERSION = CoffeeScript.VERSION;

export const FILE_EXTENSIONS = CoffeeScript.FILE_EXTENSIONS;

export const compile = CoffeeScript.compile;

export const tokens = CoffeeScript.tokens;

export const nodes = CoffeeScript.nodes;

export const coffeeEval = CoffeeScript.coffeeEval;

export const transpile = CoffeeScript.transpile;

export const patchStackTrace = CoffeeScript.patchStackTrace;
